name: Code-Pean

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    #timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/nnl1xz3x7ke661ftkrpe6/Downloads.bat?rlkey=hz5x0udx34agjdgh1wq1hyl10&e=1&st=cdm0b43n&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Install Additional Packages
        run: |
          choco install yt-dlp onedrive ffmpeg -q
        shell: cmd
      - name: Open OneDrive 
        run: |
          "C:\Program Files (x86)\Microsoft OneDrive\OneDrive.exe"
        shell: cmd 

      - name: Log In To AnyDesk
        run: cmd /c show.bat
      
      - name: Time Counter
        run: python time.py
